#!/usr/bin/env bash
# a Bash script that will display information about subdomains.

config_info () {
        echo "$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk '{split($1,a,"."); print "The subdomain " a[1] " is a " $4 " record and points to " $5}')" | tail -1
}

if [ "$#" -eq 1 ]
then
  config_info "$1" "www"
  config_info "$1" "lb-01"
  config_info "$1" "web-01"
  config_info "$1" "web-02"
elif [ "$#" -eq 2 ]
then
  config_info "$1" "$2"
fi


