#!/usr/bin/env bash
# a Bash script that will display information about subdomains.

config_info () {
	echo "$2 $(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')" | awk '{print "The subdomain " $1" is a " $2 " record and points to " $3}'
}

config_info () {
    dig "$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4, $5}'


if [ "$#" -eq 1 ]
then
  config_info "$1" "www"
  config_info "$1" "lb-01"
  config_info "$1" "web-01"
  config_info "$1" "web-02"
elif [ "$#" -eq 2 ]
then
  config_info "$1" "$2"
fi